# Generated by Django 5.2.8 on 2025-11-15 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Heritagedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heritage',
            name='location',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=100)),
                ('heritage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_info', to='Heritagedb.heritage')),
            ],
        ),
    ]
